version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: freelance-db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=freelance_db
    ports: 
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: